language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ZVtVOnrNsk2KW7ggQnsLRgOjlNVKuPOZkRkl+clWLulsNFqMjlQGl7smthNSgrerlC6TvGW0PI8r29+6fJO5a5r50MlLTlsX1G0Llib6N6Cz0i0wUQtDQ+hYUYyaCOooI3TxN+CtN9sv7+EIRz6JfuAy6K3wNuNYgAdjUvgtWdbYRz57/DMHFMBMFlSsb+T5ZYYWlrpDqLJRhysPWCKkpKCRXX7WIGm3lGKDUrvv+0vBotrxCzGtqkhHzKUsGH5nhOwIwSVOSQ5ph9nb2H9IvoiDK9DrFpEH4tHT+TAu9sTH9hwElyb4U7x5Y5/22Dj0kaVh8A/Aebz4uhC1DFDKyLUB5XEJgFYNZTYi+HJklczj5GUJBAX02WmK+pZnwZ3uaXzwXVvMYMukoI4Mhlc10Kh0J+Lx/QUAFpTGn21Vx2r9mEczcu4UwuqV+EjicFivLIqN0gCERwJ+5urGn3NJ6ReW1gkIM4i8feSmOioVRr84vZVDIU+IVKyUBTScSoQASuNCxzTJ24Kwd8N5PQP2IGo7FyjTaLtb0dzTTAArPAz6pMPiwnQ8xZXyrl7TiP4fKT3wPYEDM5si8YQWxa5vl1f5rB4JGto8F2I8nKhedhlLiTfgMlhjpCjo1xEK672qEXngbVvOVDUZNCZxHhQ4CGI6f6unTdK+2DjuyWyl49M=
  app: morning-sierra-25621
  on:
    repo: Tzikas/socket
